#pragma once


enum ROTATION { X, Y, Z };

enum TEXTYPE { TEX_SINGLE, TEX_MULTI, TEX_END };

enum ANI_TYPE { ANI_LOOP, ANI_ONCE, ANI_END };

namespace OBSERVER
{
	enum DATAID { PLAYER_INFO, PLAYER_STATUS, PLAYER_MONEY, BOSS_STATUS, DATA_END };
}

enum MAPCHANGE { NO_CHANGE, YES_CHANGE, NOT_WORK };

namespace OBJECT
{
	enum TYPE { PLAYER, ENEMY, NPC, ARROW, BOSS, DAGGER, POISIONBOMB, PLAYER_ATTACK, ENEMY_ATTACK, EFFECT, TILE, MONEY, END };
}

enum ITEMTYPE { ACTIVE, PASSIVE, IMPORTANT, ITEMTYPE_END };
